<?php

/**
 *    Zenbership
 *    http://www.zenbership.com/
 *    (c) 2012, Castlamp.
 *
 *    Purpose: User management page:
 *    -> Update Account
 *
 *    WARNING!
 *    DO NOT EDIT THIS FILE!
 *    To change the calendar's
 *    apperance, please edit the
 *    program templates from the
 *    "Integration" section of the
 *    admin control panel.
 *
 */
// Load the basics
require "../admin/sd-system/config.php";
// Check for SSL
$ssl            = $db->force_ssl('1');
// Check a user's session
$session = new session;
$ses     = $session->check_session();
if ($ses['error'] == '1') {
    $session->reject('login', $ses['ecode']);
    exit;
} else {
    // Member
    $user   = new user;
    $member = $user->get_user($ses['member_id']);
    /**
     * Pagination
     */
    $add_get = array();
    $filters = array(
        'ppSD_cart_billing.member_id' => array('scope' => 'AND', 'value' => $ses['member_id'], 'eq' => 'eq'),
        'ppSD_cart_billing.method'    => array('scope' => 'AND', 'value' => 'Credit Card', 'eq' => 'eq'),
        'ppSD_cart_billing.cc_number' => array('scope' => 'AND', 'value' => '', 'eq' => 'neq'),
    );
    $join    = array();
    if (empty($_GET['organize'])) {
        $_GET['organize'] = '';
    }
    if (empty($_GET['order'])) {
        $_GET['order'] = 'ppSD_cart_billing.card_type';
    }
    if (empty($_GET['dir'])) {
        $_GET['dir'] = 'ASC';
    }
    if (empty($_GET['display'])) {
        $_GET['display'] = '24';
    }
    $paginate  = new pagination('ppSD_cart_billing', 'manage/credit_cards.php', $add_get, $_GET, $filters, $join, '*');
    $cart      = new cart;
    $formatted = '';
    $STH       = $db->run_query($paginate->query);
    while ($row = $STH->fetch()) {
        $changes = $cart->decode_card($row);
        $formatted .= new template('manage_credit_cards_entry', $changes, '0');
        //pa($order);
    }
    // Billing History
    //pa($pagination);
    // Template
    $changes = array(
        'cards'      => $formatted,
        'pagination' => $paginate->rendered_pages
    );
    $wrapper = new template('manage_credit_cards', $changes, '1');
    echo $wrapper;
    exit;
}

